version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'direct'
    groups:
      next:
        patterns:
          - 'next'
          - 'eslint-config-next'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      jest:
        patterns:
          - 'jest*'
          - '@types/jest*'
          - '@swc/jest'

  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'daily'
